server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: test-alpha
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/test_alpha
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

debug: true
#type: default